name: Keep Render App Warm

on:
  schedule:
    - cron: '*/25 * * * *'  # Runs every 25 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request and log response
        run: curl -v https://your-portfolio-url.com
